source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target ‘IOGank’ do
	
	pod 'Alamofire', '~> 4.0.0'
	#pod 'Kingfisher', '~> 2.5.1'
	#pod 'SwiftyJSON', '~> 2.3.2'
	#pod 'SnapKit', '~> 0.30.0.beta2'
	#pod 'BSImagePicker', '~> 2.3.0'

end